version: "3.8"
services:
  backend:
    container_name: iris
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    # env_file: .env
    networks:
      - trandung
networks:
  trandung: